dist: xenial
group: travis_latest
language: node_js
node_js:
  - "8"
  - "10"
  - "11"
  - "12"

before_install:
  - docker-compose up --build -d
install:
  - docker-compose exec messaging yarn install
script:
  - docker-compose exec -e DEBUG=false messaging yarn test:ci
