version: '3.6'
services:

  messaging:
    build:
      context: .
      target: dev
    environment:
      - RABBIT_URI=amqp://rabbit
    volumes:
      - ./:/app/
    depends_on:
      - rabbit

  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
      - 1234:15672
      - 5672
